name = "parallelcoinexplorer"
type = "webpack"
route = ''
account_id = '6f4924137f40d1ae80786e8a115d2e64'
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
